lint_module = odsexport
test_module = odsexport.tests

[coverage.ignore]
# These files are all from my pycommon library
src/odsexport/cli/FriendlyArgumentParser.py
src/odsexport/cli/MultiCommand.py
src/odsexport/cli/PrefixMatcher.py

[linter.disable]
src.odsexport.Formula:Expression.__sub__:not-callable
src.odsexport.Formula:Expression.__mul__:not-callable
src.odsexport.Formula:Expression.__truediv__:not-callable
src.odsexport.Formula:Expression.__mod__:not-callable
src.odsexport.Formula:Expression.__neg__:not-callable
src.odsexport.Formula:Expression.__pow__:not-callable
src.odsexport.Formula:Expression.__lt__:not-callable
src.odsexport.Formula:Expression.__le__:not-callable
src.odsexport.Formula:Expression.__gt__:not-callable
src.odsexport.Formula:Expression.__ge__:not-callable
src.odsexport.Formula:Expression.__eq__:not-callable
src.odsexport.Formula:Expression.__ne__:not-callable
src.odsexport.Formula:Expression.__and__:not-callable
src.odsexport.Formula:Expression.__or__:not-callable
src.odsexport.Formula:Expression.__invert__:not-callable
src.odsexport.Formula:Expression._symmetric_round_positive_value:not-callable
src.odsexport.Formula:Expression._possibly_subtotal:not-callable
src.odsexport.Formula:Expression.abs:not-callable
src.odsexport.Formula:Expression.sign:not-callable
src.odsexport.Formula:Expression.is_even:not-callable
src.odsexport.Formula:Expression.is_odd:not-callable
src.odsexport.Formula:Expression.round:not-callable
src.odsexport.Formula:Expression.round_up:not-callable
src.odsexport.Formula:Expression.clamp:not-callable
src.odsexport.Formula:Expression.then:not-callable
src.odsexport.Formula:Expression.__add__:not-callable
src.odsexport.Formula:Expression.count_if:not-callable
src.odsexport.Formula:Expression.wrap:not-callable

src.odsexport.Formula:Expression.count_if:isinstance-second-argument-not-valid-type
src.odsexport.Formula:Expression.wrap:isinstance-second-argument-not-valid-type
src.odsexport.Formula:UnaryOperation.render:isinstance-second-argument-not-valid-type

src.odsexport.cli.FriendlyArgumentParser:*:*
src.odsexport.cli.MultiCommand:*:*
src.odsexport.cli.PrefixMatcher:*:*

*:*:missing-function-docstring
*:*:missing-module-docstring
*:*:missing-class-docstring
*:*:invalid-name
*:*:duplicate-code
*:*:too-few-public-methods
*:*:superfluous-parens
*:*:too-many-arguments
*:*:protected-access
*:*:multiple-statements
*:*:too-many-branches
*:*:too-many-public-methods
*:*:attribute-defined-outside-init
*:*:unspecified-encoding
*:*:unused-variable
*:*:fixme
*:*:unused-argument
*:*:too-many-instance-attributes
*:*:no-else-return
*:*:arguments-renamed
*:*:redefined-outer-name
*:*:too-many-locals
*:*:no-else-raise
*:*:broad-except
*:*:too-many-nested-blocks
*:*:useless-super-delegation
*:*:consider-using-max-builtin

[linter.enable]
*:*:unused-import
*:*:raise-missing-from
*:*:anomalous-backslash-in-string
*:*:wrong-import-order
*:*:inconsistent-return-statements
*:*:logging-fstring-interpolation
*:*:f-string-without-interpolation
*:*:consider-using-max-builtin
*:*:subprocess-run-check

# vim:syntax=dosini
